# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy
on:
  release:
    types: [published]

jobs:
  vsce:
    name: VS Code Marketplace
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: VS Code Marketplace
      url: https://marketplace.visualstudio.com/items?itemName=johnbillion.vscode-wordpress-hooks
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: clean install dependencies
        run: npm ci

      - name: deploy
        run: npm run deploy-vsce -- -p ${{ secrets.VSCE_TOKEN }}

  openvsx:
    name: Open VSX
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: Open VSX Registry
      url: https://open-vsx.org/extension/johnbillion/vscode-wordpress-hooks
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: clean install dependencies
        run: npm ci

      - name: deploy
        run: npm run deploy-openvsx -- -p ${{ secrets.OVSX_TOKEN }}

  github:
    name: GitHub Milestones
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Get next versions
      id: semvers
      uses: WyriHaximus/github-action-next-semvers@v1.0
      with:
        version: ${{ github.event.release.tag_name }}

    - name: Create next patch milestone
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:repository/milestones
        repository: ${{ github.repository }}
        title: ${{ steps.semvers.outputs.patch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Create next minor milestone
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:repository/milestones
        repository: ${{ github.repository }}
        title: ${{ steps.semvers.outputs.minor }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Create next major milestone
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/:repository/milestones
        repository: ${{ github.repository }}
        title: ${{ steps.semvers.outputs.major }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
