# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test

on:
  push:
  pull_request:

jobs:
  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Run Linting
      run: npm run lint

    - name: Run the build
      run: npm run build
